export type AuthLang = 'el' | 'en'

const STRINGS = {
  el: {
    signupTitle: 'Για να συνεχίσεις, συμπλήρωσε τα στοιχεία σου!',
    loginTitle: 'Καλωσήρθες πίσω!',
    name: 'Όνομα',
    namePh: 'Το όνομά σου',
    email: 'Email',
    emailPh: 'you@example.com',
    password: 'Κωδικός πρόσβασης',
    passwordPh: 'Εισαγάγετε κωδικό πρόσβασης',
    inviteTitle: 'Έχεις κωδικό πρόσκλησης;',
    invitePh: 'π.χ. HEYMAA-ABC123',
    wantChild: 'Θέλω να αποκτήσω παιδί',
    pregnantOrMom: 'Είμαι έγκυος ή μαμά',
    newsletter:
      'Θέλω να λαμβάνω ενημερώσεις και newsletters με χρήσιμες συμβουλές για τη μητρότητα.',
    privacy: 'Έχω διαβάσει και αποδέχομαι την',
    privacyLink: 'Πολιτική Προστασίας Προσωπικών Δεδομένων',
    terms: 'Αποδέχομαι τους',
    termsLink: 'Όρους και Προϋποθέσεις',
    register: 'Εγγραφή',
    registering: 'Εγγραφή…',
    or: 'ή',
    google: 'Συνέχεια με Google',
    googleSoon: 'Η σύνδεση με Google θα είναι σύντομα διαθέσιμη.',
    hasAccount: 'Έχεις ήδη λογαριασμό;',
    login: 'Σύνδεση',
    noAccount: 'Δεν έχεις λογαριασμό;',
    signup: 'Εγγραφή',
    loginBtn: 'Είσοδος',
    loggingIn: 'Σύνδεση…',
    forgot: 'Ξέχασες τον κωδικό;',
    errConnection: 'Σφάλμα σύνδεσης.',
    errPasswordMin: 'Ο κωδικός πρέπει να έχει τουλάχιστον 6 χαρακτήρες.',
    errName: 'Συμπλήρωσε το όνομά σου.',
    errPrivacy: 'Αποδέχσου την Πολιτική Προστασίας Προσωπικών Δεδομένων.',
    errTerms: 'Αποδέχσου τους Όρους και Προϋποθέσεις.',
    errLogin: 'Λάθος email ή κωδικός.',
    errRegister: 'Αποτυχία εγγραφής.',
    errEmailExists: 'Το email είναι ήδη καταχωρημένο.',
  },
  en: {
    signupTitle: 'To continue, fill in your details!',
    loginTitle: 'Welcome back!',
    name: 'Name',
    namePh: 'Your name',
    email: 'Email',
    emailPh: 'you@example.com',
    password: 'Password',
    passwordPh: 'Enter your password',
    inviteTitle: 'Have an invite code?',
    invitePh: 'e.g. HEYMAA-ABC123',
    wantChild: 'I want to have a child',
    pregnantOrMom: 'I am pregnant or a mom',
    newsletter: 'I want to receive updates and newsletters with useful motherhood tips.',
    privacy: 'I have read and accept the',
    privacyLink: 'Privacy Policy',
    terms: 'I accept the',
    termsLink: 'Terms and Conditions',
    register: 'Sign up',
    registering: 'Signing up…',
    or: 'or',
    google: 'Continue with Google',
    googleSoon: 'Google sign-in will be available soon.',
    hasAccount: 'Already have an account?',
    login: 'Log in',
    noAccount: "Don't have an account?",
    signup: 'Sign up',
    loginBtn: 'Sign in',
    loggingIn: 'Signing in…',
    forgot: 'Forgot password?',
    errConnection: 'Connection error.',
    errPasswordMin: 'Password must be at least 6 characters.',
    errName: 'Please enter your name.',
    errPrivacy: 'Please accept the Privacy Policy.',
    errTerms: 'Please accept the Terms and Conditions.',
    errLogin: 'Wrong email or password.',
    errRegister: 'Registration failed.',
    errEmailExists: 'Email is already registered.',
  },
} as const

export function authStrings(lang: AuthLang) {
  return STRINGS[lang] || STRINGS.el
}

export const PRIVACY_URL = 'https://heymaa.vdarpp.com/privacy'
export const TERMS_URL = 'https://heymaa.vdarpp.com/terms'
